# Generated by Django 4.0.5 on 2022-06-05 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=70, unique=True, verbose_name='作者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comic_name', models.CharField(max_length=100, unique=True, verbose_name='漫画名')),
                ('remarks', models.CharField(max_length=200, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('author_1', models.ForeignKey(max_length=70, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='re_author_1', to='e_comic_app.author', verbose_name='作者1')),
                ('author_2', models.ForeignKey(max_length=70, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='re_author_1', to='e_comic_app.author', verbose_name='作者2')),
                ('author_3', models.ForeignKey(max_length=70, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='re_author_1', to='e_comic_app.author', verbose_name='作者3')),
                ('author_4', models.ForeignKey(max_length=70, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='re_author_1', to='e_comic_app.author', verbose_name='作者4')),
            ],
        ),
    ]
