# Generated by Django 4.0.5 on 2022-07-02 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('e_comic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='author_2',
            field=models.ForeignKey(max_length=70, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='re_author_2', to='e_comic_app.author', verbose_name='作者2'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='author_3',
            field=models.ForeignKey(max_length=70, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='re_author_3', to='e_comic_app.author', verbose_name='作者3'),
        ),
        migrations.AlterField(
            model_name='comic',
            name='author_4',
            field=models.ForeignKey(max_length=70, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='re_author_4', to='e_comic_app.author', verbose_name='作者4'),
        ),
    ]
